swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/transaction:
    post:
      security:
        - Bearer: []
      tags:
        - User Transaction Module
      summary: User Transaction
      description: API for fetching a user transaction
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Transcation Payload
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      produces:
        - application/json
      responses:
        "200":
          description: User transaction retrieved successfully
          schema:
            $ref: "#/definitions/TransactionResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/monthlyTransactions:
    post:
      security:
        - Bearer: []
      tags:
        - User Monthly Transactions Module
      summary: User's current month transactions
      description: API for fetching the transactions carried out during the current month by the user
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: User transactions retrieved successfully
          schema:
            $ref: "#/definitions/MonthlyTransactionsResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/transactions/summary:
    post:
      security:
        - Bearer: []
      tags:
        - User Monthly Transactions Module
      summary: User Summary Transaction Informations
      description: API for fetching user summary transaction
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: User transactions summary retrieved successfully
          schema:
            $ref: "#/definitions/SummaryResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  Transaction:
    properties:
      id:
        type: string
        description: user transaction id
  TransactionResponse:
    type: object
    properties:
      amount:
        type: number
        description: transaction amount
      date:
        type: string
        description: transaction date
      description:
        type: string
        description: transaction description
      transactionInformations:
        type: object
        description: object containing the type, category and note of the transaction
        example:
          {
            transactionId: string,
            type: string,
            category: string,
            note: string,
          }
      id:
        type: string
        description: transaction id
    example:
      {
        amount: number,
        date: string,
        description: string,
        transactionInformations: object,
        id: string,
      }
  MonthlyTransactionsResponse:
    type: array
    items:
      type: object
    example:
      [
        {
          amount: number,
          date: string,
          description: string,
          transactionInformations: object,
          id: string,
        },
      ]
    description: current month transactions
  SummaryResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        properties:
          checkings:
            type: number
          savings:
            type: number
          card:
            type: number
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string